# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: catalogo_filmes_rails_development

  # üëáüëáüëá √â AQUI QUE VOC√ä PRECISA EDITAR üëáüëáüëá

  # Coloque seu usu√°rio do PostgreSQL (o padr√£o √© 'postgres')
  username: postgres

  # Coloque a SENHA que voc√™ definiu ao instalar o PostgreSQL
  password: Mineple1

  # Essas linhas ajudam a garantir a conex√£o
  host: localhost
  port: 5432

  # üëÜüëÜüëÜ FIM DA EDI√á√ÉO üëÜüëÜüëÜ


test:
  <<: *default
  database: catalogo_filmes_rails_test


  username: postgres
  password: Mineple1
  host: localhost
  port: 5432


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  cable:
    url: <%= ENV['DATABASE_URL'] %>
# Verifica√ß√£o final para o deploy